// Copyright (c) Josef Pihrt. All rights reserved. Licensed under the Apache License, Version 2.0. See License.txt in the project root for license information.

// <auto-generated>

namespace Roslynator.CSharp
{
    internal static partial class CompilerDiagnosticIdentifiers
    {
        internal const string Zero = "CS0000";
    }
}