// Copyright (c) Josef Pihrt. All rights reserved. Licensed under the Apache License, Version 2.0. See License.txt in the project root for license information.

// <auto-generated>

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Roslynator.CSharp.SyntaxWalkers
{
    public class OnlyVisitMethodWalker : CSharpSyntaxWalker
    {
        public OnlyVisitMethodWalker(): base (depth: SyntaxWalkerDepth.Node)
        {
        }

        protected virtual bool ShouldVisit
        {
            get
            {
                return true;
            }
        }

        public override void Visit(SyntaxNode node)
        {
            if (!ShouldVisit)
            {
                return;
            }

            base.Visit(node);
        }

        private void VisitList<TNode>(SyntaxList<TNode> list)where TNode : SyntaxNode
        {
            foreach (TNode node in list)
            {
                if (!ShouldVisit)
                {
                    return;
                }

                Visit(node);
            }
        }

        private void VisitSeparatedList<TNode>(SeparatedSyntaxList<TNode> list)where TNode : SyntaxNode
        {
            foreach (TNode node in list)
            {
                if (!ShouldVisit)
                {
                    return;
                }

                Visit(node);
            }
        }

        public override void VisitAccessorDeclaration(AccessorDeclarationSyntax node)
        {
            VisitList(node.AttributeLists);
            Visit(node.Body);
            Visit(node.ExpressionBody);
        }

        public override void VisitAccessorList(AccessorListSyntax node)
        {
            VisitList(node.Accessors);
        }

        public override void VisitAliasQualifiedName(AliasQualifiedNameSyntax node)
        {
            Visit(node.Alias);
            Visit(node.Name);
        }

        public override void VisitAnonymousMethodExpression(AnonymousMethodExpressionSyntax node)
        {
            Visit(node.ParameterList);
            Visit(node.Body);
        }

        public override void VisitAnonymousObjectCreationExpression(AnonymousObjectCreationExpressionSyntax node)
        {
            VisitSeparatedList(node.Initializers);
        }

        public override void VisitAnonymousObjectMemberDeclarator(AnonymousObjectMemberDeclaratorSyntax node)
        {
            Visit(node.NameEquals);
            Visit(node.Expression);
        }

        public override void VisitArgument(ArgumentSyntax node)
        {
            Visit(node.NameColon);
            Visit(node.Expression);
        }

        public override void VisitArgumentList(ArgumentListSyntax node)
        {
            VisitSeparatedList(node.Arguments);
        }

        public override void VisitArrayCreationExpression(ArrayCreationExpressionSyntax node)
        {
            Visit(node.Type);
            Visit(node.Initializer);
        }

        public override void VisitArrayRankSpecifier(ArrayRankSpecifierSyntax node)
        {
            VisitSeparatedList(node.Sizes);
        }

        public override void VisitArrayType(ArrayTypeSyntax node)
        {
            Visit(node.ElementType);
            VisitList(node.RankSpecifiers);
        }

        public override void VisitArrowExpressionClause(ArrowExpressionClauseSyntax node)
        {
            Visit(node.Expression);
        }

        public override void VisitAssignmentExpression(AssignmentExpressionSyntax node)
        {
            Visit(node.Left);
            Visit(node.Right);
        }

        public override void VisitAttribute(AttributeSyntax node)
        {
            Visit(node.Name);
            Visit(node.ArgumentList);
        }

        public override void VisitAttributeArgument(AttributeArgumentSyntax node)
        {
            Visit(node.NameEquals);
            Visit(node.NameColon);
            Visit(node.Expression);
        }

        public override void VisitAttributeArgumentList(AttributeArgumentListSyntax node)
        {
            VisitSeparatedList(node.Arguments);
        }

        public override void VisitAttributeList(AttributeListSyntax node)
        {
            Visit(node.Target);
            VisitSeparatedList(node.Attributes);
        }

        public override void VisitAttributeTargetSpecifier(AttributeTargetSpecifierSyntax node)
        {
        }

        public override void VisitAwaitExpression(AwaitExpressionSyntax node)
        {
            Visit(node.Expression);
        }

        public override void VisitBadDirectiveTrivia(BadDirectiveTriviaSyntax node)
        {
        }

        public override void VisitBaseExpression(BaseExpressionSyntax node)
        {
        }

        public override void VisitBaseList(BaseListSyntax node)
        {
            VisitSeparatedList(node.Types);
        }

        public override void VisitBinaryExpression(BinaryExpressionSyntax node)
        {
            Visit(node.Left);
            Visit(node.Right);
        }

        public override void VisitBlock(BlockSyntax node)
        {
            VisitList(node.Statements);
        }

        public override void VisitBracketedArgumentList(BracketedArgumentListSyntax node)
        {
            VisitSeparatedList(node.Arguments);
        }

        public override void VisitBracketedParameterList(BracketedParameterListSyntax node)
        {
            VisitSeparatedList(node.Parameters);
        }

        public override void VisitBreakStatement(BreakStatementSyntax node)
        {
        }

        public override void VisitCasePatternSwitchLabel(CasePatternSwitchLabelSyntax node)
        {
            Visit(node.Pattern);
            Visit(node.WhenClause);
        }

        public override void VisitCaseSwitchLabel(CaseSwitchLabelSyntax node)
        {
            Visit(node.Value);
        }

        public override void VisitCastExpression(CastExpressionSyntax node)
        {
            Visit(node.Type);
            Visit(node.Expression);
        }

        public override void VisitCatchClause(CatchClauseSyntax node)
        {
            Visit(node.Declaration);
            Visit(node.Filter);
            Visit(node.Block);
        }

        public override void VisitCatchDeclaration(CatchDeclarationSyntax node)
        {
            Visit(node.Type);
        }

        public override void VisitCatchFilterClause(CatchFilterClauseSyntax node)
        {
            Visit(node.FilterExpression);
        }

        public override void VisitClassDeclaration(ClassDeclarationSyntax node)
        {
            VisitList(node.AttributeLists);
            Visit(node.TypeParameterList);
            Visit(node.BaseList);
            VisitList(node.ConstraintClauses);
            VisitList(node.Members);
        }

        public override void VisitClassOrStructConstraint(ClassOrStructConstraintSyntax node)
        {
        }

        public override void VisitCompilationUnit(CompilationUnitSyntax node)
        {
            VisitList(node.Externs);
            VisitList(node.Usings);
            VisitList(node.AttributeLists);
            VisitList(node.Members);
        }

        public override void VisitConditionalAccessExpression(ConditionalAccessExpressionSyntax node)
        {
            Visit(node.Expression);
            Visit(node.WhenNotNull);
        }

        public override void VisitConditionalExpression(ConditionalExpressionSyntax node)
        {
            Visit(node.Condition);
            Visit(node.WhenTrue);
            Visit(node.WhenFalse);
        }

        public override void VisitConstantPattern(ConstantPatternSyntax node)
        {
            Visit(node.Expression);
        }

        public override void VisitConstructorConstraint(ConstructorConstraintSyntax node)
        {
        }

        public override void VisitConstructorDeclaration(ConstructorDeclarationSyntax node)
        {
            VisitList(node.AttributeLists);
            Visit(node.ParameterList);
            Visit(node.Initializer);
            Visit(node.Body);
            Visit(node.ExpressionBody);
        }

        public override void VisitConstructorInitializer(ConstructorInitializerSyntax node)
        {
            Visit(node.ArgumentList);
        }

        public override void VisitContinueStatement(ContinueStatementSyntax node)
        {
        }

        public override void VisitConversionOperatorDeclaration(ConversionOperatorDeclarationSyntax node)
        {
            VisitList(node.AttributeLists);
            Visit(node.Type);
            Visit(node.ParameterList);
            Visit(node.Body);
            Visit(node.ExpressionBody);
        }

        public override void VisitConversionOperatorMemberCref(ConversionOperatorMemberCrefSyntax node)
        {
            Visit(node.Type);
            Visit(node.Parameters);
        }

        public override void VisitCrefBracketedParameterList(CrefBracketedParameterListSyntax node)
        {
            VisitSeparatedList(node.Parameters);
        }

        public override void VisitCrefParameter(CrefParameterSyntax node)
        {
            Visit(node.Type);
        }

        public override void VisitCrefParameterList(CrefParameterListSyntax node)
        {
            VisitSeparatedList(node.Parameters);
        }

        public override void VisitDeclarationExpression(DeclarationExpressionSyntax node)
        {
            Visit(node.Type);
            Visit(node.Designation);
        }

        public override void VisitDeclarationPattern(DeclarationPatternSyntax node)
        {
            Visit(node.Type);
            Visit(node.Designation);
        }

        public override void VisitDefaultExpression(DefaultExpressionSyntax node)
        {
            Visit(node.Type);
        }

        public override void VisitDefaultSwitchLabel(DefaultSwitchLabelSyntax node)
        {
        }

        public override void VisitDefineDirectiveTrivia(DefineDirectiveTriviaSyntax node)
        {
        }

        public override void VisitDelegateDeclaration(DelegateDeclarationSyntax node)
        {
            VisitList(node.AttributeLists);
            Visit(node.ReturnType);
            Visit(node.TypeParameterList);
            Visit(node.ParameterList);
            VisitList(node.ConstraintClauses);
        }

        public override void VisitDestructorDeclaration(DestructorDeclarationSyntax node)
        {
            VisitList(node.AttributeLists);
            Visit(node.ParameterList);
            Visit(node.Body);
            Visit(node.ExpressionBody);
        }

        public override void VisitDiscardDesignation(DiscardDesignationSyntax node)
        {
        }

        public override void VisitDocumentationCommentTrivia(DocumentationCommentTriviaSyntax node)
        {
            VisitList(node.Content);
        }

        public override void VisitDoStatement(DoStatementSyntax node)
        {
            Visit(node.Statement);
            Visit(node.Condition);
        }

        public override void VisitElementAccessExpression(ElementAccessExpressionSyntax node)
        {
            Visit(node.Expression);
            Visit(node.ArgumentList);
        }

        public override void VisitElementBindingExpression(ElementBindingExpressionSyntax node)
        {
            Visit(node.ArgumentList);
        }

        public override void VisitElifDirectiveTrivia(ElifDirectiveTriviaSyntax node)
        {
            Visit(node.Condition);
        }

        public override void VisitElseClause(ElseClauseSyntax node)
        {
            Visit(node.Statement);
        }

        public override void VisitElseDirectiveTrivia(ElseDirectiveTriviaSyntax node)
        {
        }

        public override void VisitEmptyStatement(EmptyStatementSyntax node)
        {
        }

        public override void VisitEndIfDirectiveTrivia(EndIfDirectiveTriviaSyntax node)
        {
        }

        public override void VisitEndRegionDirectiveTrivia(EndRegionDirectiveTriviaSyntax node)
        {
        }

        public override void VisitEnumDeclaration(EnumDeclarationSyntax node)
        {
            VisitList(node.AttributeLists);
            Visit(node.BaseList);
            VisitSeparatedList(node.Members);
        }

        public override void VisitEnumMemberDeclaration(EnumMemberDeclarationSyntax node)
        {
            VisitList(node.AttributeLists);
            Visit(node.EqualsValue);
        }

        public override void VisitEqualsValueClause(EqualsValueClauseSyntax node)
        {
            Visit(node.Value);
        }

        public override void VisitErrorDirectiveTrivia(ErrorDirectiveTriviaSyntax node)
        {
        }

        public override void VisitEventDeclaration(EventDeclarationSyntax node)
        {
            VisitList(node.AttributeLists);
            Visit(node.Type);
            Visit(node.ExplicitInterfaceSpecifier);
            Visit(node.AccessorList);
        }

        public override void VisitEventFieldDeclaration(EventFieldDeclarationSyntax node)
        {
            VisitList(node.AttributeLists);
            Visit(node.Declaration);
        }

        public override void VisitExplicitInterfaceSpecifier(ExplicitInterfaceSpecifierSyntax node)
        {
            Visit(node.Name);
        }

        public override void VisitExpressionStatement(ExpressionStatementSyntax node)
        {
            Visit(node.Expression);
        }

        public override void VisitExternAliasDirective(ExternAliasDirectiveSyntax node)
        {
        }

        public override void VisitFieldDeclaration(FieldDeclarationSyntax node)
        {
            VisitList(node.AttributeLists);
            Visit(node.Declaration);
        }

        public override void VisitFinallyClause(FinallyClauseSyntax node)
        {
            Visit(node.Block);
        }

        public override void VisitFixedStatement(FixedStatementSyntax node)
        {
            Visit(node.Declaration);
            Visit(node.Statement);
        }

        public override void VisitForEachStatement(ForEachStatementSyntax node)
        {
            Visit(node.Type);
            Visit(node.Expression);
            Visit(node.Statement);
        }

        public override void VisitForEachVariableStatement(ForEachVariableStatementSyntax node)
        {
            Visit(node.Variable);
            Visit(node.Expression);
            Visit(node.Statement);
        }

        public override void VisitForStatement(ForStatementSyntax node)
        {
            Visit(node.Declaration);
            VisitSeparatedList(node.Initializers);
            Visit(node.Condition);
            VisitSeparatedList(node.Incrementors);
            Visit(node.Statement);
        }

        public override void VisitFromClause(FromClauseSyntax node)
        {
            Visit(node.Type);
            Visit(node.Expression);
        }

        public override void VisitGenericName(GenericNameSyntax node)
        {
            Visit(node.TypeArgumentList);
        }

        public override void VisitGlobalStatement(GlobalStatementSyntax node)
        {
            Visit(node.Statement);
        }

        public override void VisitGotoStatement(GotoStatementSyntax node)
        {
            Visit(node.Expression);
        }

        public override void VisitGroupClause(GroupClauseSyntax node)
        {
            Visit(node.GroupExpression);
            Visit(node.ByExpression);
        }

        public override void VisitCheckedExpression(CheckedExpressionSyntax node)
        {
            Visit(node.Expression);
        }

        public override void VisitCheckedStatement(CheckedStatementSyntax node)
        {
            Visit(node.Block);
        }

        public override void VisitIdentifierName(IdentifierNameSyntax node)
        {
        }

        public override void VisitIfDirectiveTrivia(IfDirectiveTriviaSyntax node)
        {
            Visit(node.Condition);
        }

        public override void VisitIfStatement(IfStatementSyntax node)
        {
            Visit(node.Condition);
            Visit(node.Statement);
            Visit(node.Else);
        }

        public override void VisitImplicitArrayCreationExpression(ImplicitArrayCreationExpressionSyntax node)
        {
            Visit(node.Initializer);
        }

        public override void VisitImplicitElementAccess(ImplicitElementAccessSyntax node)
        {
            Visit(node.ArgumentList);
        }

        public override void VisitIncompleteMember(IncompleteMemberSyntax node)
        {
            VisitList(node.AttributeLists);
            Visit(node.Type);
        }

        public override void VisitIndexerDeclaration(IndexerDeclarationSyntax node)
        {
            VisitList(node.AttributeLists);
            Visit(node.Type);
            Visit(node.ExplicitInterfaceSpecifier);
            Visit(node.ParameterList);
            Visit(node.AccessorList);
            Visit(node.ExpressionBody);
        }

        public override void VisitIndexerMemberCref(IndexerMemberCrefSyntax node)
        {
            Visit(node.Parameters);
        }

        public override void VisitInitializerExpression(InitializerExpressionSyntax node)
        {
            VisitSeparatedList(node.Expressions);
        }

        public override void VisitInterfaceDeclaration(InterfaceDeclarationSyntax node)
        {
            VisitList(node.AttributeLists);
            Visit(node.TypeParameterList);
            Visit(node.BaseList);
            VisitList(node.ConstraintClauses);
            VisitList(node.Members);
        }

        public override void VisitInterpolatedStringExpression(InterpolatedStringExpressionSyntax node)
        {
            VisitList(node.Contents);
        }

        public override void VisitInterpolatedStringText(InterpolatedStringTextSyntax node)
        {
        }

        public override void VisitInterpolation(InterpolationSyntax node)
        {
            Visit(node.Expression);
            Visit(node.AlignmentClause);
            Visit(node.FormatClause);
        }

        public override void VisitInterpolationAlignmentClause(InterpolationAlignmentClauseSyntax node)
        {
            Visit(node.Value);
        }

        public override void VisitInterpolationFormatClause(InterpolationFormatClauseSyntax node)
        {
        }

        public override void VisitInvocationExpression(InvocationExpressionSyntax node)
        {
            Visit(node.Expression);
            Visit(node.ArgumentList);
        }

        public override void VisitIsPatternExpression(IsPatternExpressionSyntax node)
        {
            Visit(node.Expression);
            Visit(node.Pattern);
        }

        public override void VisitJoinClause(JoinClauseSyntax node)
        {
            Visit(node.Type);
            Visit(node.InExpression);
            Visit(node.LeftExpression);
            Visit(node.RightExpression);
            Visit(node.Into);
        }

        public override void VisitJoinIntoClause(JoinIntoClauseSyntax node)
        {
        }

        public override void VisitLabeledStatement(LabeledStatementSyntax node)
        {
            Visit(node.Statement);
        }

        public override void VisitLetClause(LetClauseSyntax node)
        {
            Visit(node.Expression);
        }

        public override void VisitLineDirectiveTrivia(LineDirectiveTriviaSyntax node)
        {
        }

        public override void VisitLiteralExpression(LiteralExpressionSyntax node)
        {
        }

        public override void VisitLoadDirectiveTrivia(LoadDirectiveTriviaSyntax node)
        {
        }

        public override void VisitLocalDeclarationStatement(LocalDeclarationStatementSyntax node)
        {
            Visit(node.Declaration);
        }

        public override void VisitLocalFunctionStatement(LocalFunctionStatementSyntax node)
        {
            Visit(node.ReturnType);
            Visit(node.TypeParameterList);
            Visit(node.ParameterList);
            VisitList(node.ConstraintClauses);
            Visit(node.Body);
            Visit(node.ExpressionBody);
        }

        public override void VisitLockStatement(LockStatementSyntax node)
        {
            Visit(node.Expression);
            Visit(node.Statement);
        }

        public override void VisitMakeRefExpression(MakeRefExpressionSyntax node)
        {
            Visit(node.Expression);
        }

        public override void VisitMemberAccessExpression(MemberAccessExpressionSyntax node)
        {
            Visit(node.Expression);
            Visit(node.Name);
        }

        public override void VisitMemberBindingExpression(MemberBindingExpressionSyntax node)
        {
            Visit(node.Name);
        }

        public override void VisitMethodDeclaration(MethodDeclarationSyntax node)
        {
            VisitList(node.AttributeLists);
            Visit(node.ReturnType);
            Visit(node.ExplicitInterfaceSpecifier);
            Visit(node.TypeParameterList);
            Visit(node.ParameterList);
            VisitList(node.ConstraintClauses);
            Visit(node.Body);
            Visit(node.ExpressionBody);
        }

        public override void VisitNameColon(NameColonSyntax node)
        {
            Visit(node.Name);
        }

        public override void VisitNameEquals(NameEqualsSyntax node)
        {
            Visit(node.Name);
        }

        public override void VisitNameMemberCref(NameMemberCrefSyntax node)
        {
            Visit(node.Name);
            Visit(node.Parameters);
        }

        public override void VisitNamespaceDeclaration(NamespaceDeclarationSyntax node)
        {
            Visit(node.Name);
            VisitList(node.Externs);
            VisitList(node.Usings);
            VisitList(node.Members);
        }

        public override void VisitNullableType(NullableTypeSyntax node)
        {
            Visit(node.ElementType);
        }

        public override void VisitObjectCreationExpression(ObjectCreationExpressionSyntax node)
        {
            Visit(node.Type);
            Visit(node.ArgumentList);
            Visit(node.Initializer);
        }

        public override void VisitOmittedArraySizeExpression(OmittedArraySizeExpressionSyntax node)
        {
        }

        public override void VisitOmittedTypeArgument(OmittedTypeArgumentSyntax node)
        {
        }

        public override void VisitOperatorDeclaration(OperatorDeclarationSyntax node)
        {
            VisitList(node.AttributeLists);
            Visit(node.ReturnType);
            Visit(node.ParameterList);
            Visit(node.Body);
            Visit(node.ExpressionBody);
        }

        public override void VisitOperatorMemberCref(OperatorMemberCrefSyntax node)
        {
            Visit(node.Parameters);
        }

        public override void VisitOrderByClause(OrderByClauseSyntax node)
        {
            VisitSeparatedList(node.Orderings);
        }

        public override void VisitOrdering(OrderingSyntax node)
        {
            Visit(node.Expression);
        }

        public override void VisitParameter(ParameterSyntax node)
        {
            VisitList(node.AttributeLists);
            Visit(node.Type);
            Visit(node.Default);
        }

        public override void VisitParameterList(ParameterListSyntax node)
        {
            VisitSeparatedList(node.Parameters);
        }

        public override void VisitParenthesizedExpression(ParenthesizedExpressionSyntax node)
        {
            Visit(node.Expression);
        }

        public override void VisitParenthesizedLambdaExpression(ParenthesizedLambdaExpressionSyntax node)
        {
            Visit(node.ParameterList);
            Visit(node.Body);
        }

        public override void VisitParenthesizedVariableDesignation(ParenthesizedVariableDesignationSyntax node)
        {
            VisitSeparatedList(node.Variables);
        }

        public override void VisitPointerType(PointerTypeSyntax node)
        {
            Visit(node.ElementType);
        }

        public override void VisitPostfixUnaryExpression(PostfixUnaryExpressionSyntax node)
        {
            Visit(node.Operand);
        }

        public override void VisitPragmaChecksumDirectiveTrivia(PragmaChecksumDirectiveTriviaSyntax node)
        {
        }

        public override void VisitPragmaWarningDirectiveTrivia(PragmaWarningDirectiveTriviaSyntax node)
        {
            VisitSeparatedList(node.ErrorCodes);
        }

        public override void VisitPredefinedType(PredefinedTypeSyntax node)
        {
        }

        public override void VisitPrefixUnaryExpression(PrefixUnaryExpressionSyntax node)
        {
            Visit(node.Operand);
        }

        public override void VisitPropertyDeclaration(PropertyDeclarationSyntax node)
        {
            VisitList(node.AttributeLists);
            Visit(node.Type);
            Visit(node.ExplicitInterfaceSpecifier);
            Visit(node.AccessorList);
            Visit(node.ExpressionBody);
            Visit(node.Initializer);
        }

        public override void VisitQualifiedCref(QualifiedCrefSyntax node)
        {
            Visit(node.Container);
            Visit(node.Member);
        }

        public override void VisitQualifiedName(QualifiedNameSyntax node)
        {
            Visit(node.Left);
            Visit(node.Right);
        }

        public override void VisitQueryBody(QueryBodySyntax node)
        {
            VisitList(node.Clauses);
            Visit(node.SelectOrGroup);
            Visit(node.Continuation);
        }

        public override void VisitQueryContinuation(QueryContinuationSyntax node)
        {
            Visit(node.Body);
        }

        public override void VisitQueryExpression(QueryExpressionSyntax node)
        {
            Visit(node.FromClause);
            Visit(node.Body);
        }

        public override void VisitReferenceDirectiveTrivia(ReferenceDirectiveTriviaSyntax node)
        {
        }

        public override void VisitRefExpression(RefExpressionSyntax node)
        {
            Visit(node.Expression);
        }

        public override void VisitRefType(RefTypeSyntax node)
        {
            Visit(node.Type);
        }

        public override void VisitRefTypeExpression(RefTypeExpressionSyntax node)
        {
            Visit(node.Expression);
        }

        public override void VisitRefValueExpression(RefValueExpressionSyntax node)
        {
            Visit(node.Expression);
            Visit(node.Type);
        }

        public override void VisitRegionDirectiveTrivia(RegionDirectiveTriviaSyntax node)
        {
        }

        public override void VisitReturnStatement(ReturnStatementSyntax node)
        {
            Visit(node.Expression);
        }

        public override void VisitSelectClause(SelectClauseSyntax node)
        {
            Visit(node.Expression);
        }

        public override void VisitShebangDirectiveTrivia(ShebangDirectiveTriviaSyntax node)
        {
        }

        public override void VisitSimpleBaseType(SimpleBaseTypeSyntax node)
        {
            Visit(node.Type);
        }

        public override void VisitSimpleLambdaExpression(SimpleLambdaExpressionSyntax node)
        {
            Visit(node.Parameter);
            Visit(node.Body);
        }

        public override void VisitSingleVariableDesignation(SingleVariableDesignationSyntax node)
        {
        }

        public override void VisitSizeOfExpression(SizeOfExpressionSyntax node)
        {
            Visit(node.Type);
        }

        public override void VisitSkippedTokensTrivia(SkippedTokensTriviaSyntax node)
        {
        }

        public override void VisitStackAllocArrayCreationExpression(StackAllocArrayCreationExpressionSyntax node)
        {
            Visit(node.Type);
        }

        public override void VisitStructDeclaration(StructDeclarationSyntax node)
        {
            VisitList(node.AttributeLists);
            Visit(node.TypeParameterList);
            Visit(node.BaseList);
            VisitList(node.ConstraintClauses);
            VisitList(node.Members);
        }

        public override void VisitSwitchSection(SwitchSectionSyntax node)
        {
            VisitList(node.Labels);
            VisitList(node.Statements);
        }

        public override void VisitSwitchStatement(SwitchStatementSyntax node)
        {
            Visit(node.Expression);
            VisitList(node.Sections);
        }

        public override void VisitThisExpression(ThisExpressionSyntax node)
        {
        }

        public override void VisitThrowExpression(ThrowExpressionSyntax node)
        {
            Visit(node.Expression);
        }

        public override void VisitThrowStatement(ThrowStatementSyntax node)
        {
            Visit(node.Expression);
        }

        public override void VisitTryStatement(TryStatementSyntax node)
        {
            Visit(node.Block);
            VisitList(node.Catches);
            Visit(node.Finally);
        }

        public override void VisitTupleElement(TupleElementSyntax node)
        {
            Visit(node.Type);
        }

        public override void VisitTupleExpression(TupleExpressionSyntax node)
        {
            VisitSeparatedList(node.Arguments);
        }

        public override void VisitTupleType(TupleTypeSyntax node)
        {
            VisitSeparatedList(node.Elements);
        }

        public override void VisitTypeArgumentList(TypeArgumentListSyntax node)
        {
            VisitSeparatedList(node.Arguments);
        }

        public override void VisitTypeConstraint(TypeConstraintSyntax node)
        {
            Visit(node.Type);
        }

        public override void VisitTypeCref(TypeCrefSyntax node)
        {
            Visit(node.Type);
        }

        public override void VisitTypeOfExpression(TypeOfExpressionSyntax node)
        {
            Visit(node.Type);
        }

        public override void VisitTypeParameter(TypeParameterSyntax node)
        {
            VisitList(node.AttributeLists);
        }

        public override void VisitTypeParameterConstraintClause(TypeParameterConstraintClauseSyntax node)
        {
            Visit(node.Name);
            VisitSeparatedList(node.Constraints);
        }

        public override void VisitTypeParameterList(TypeParameterListSyntax node)
        {
            VisitSeparatedList(node.Parameters);
        }

        public override void VisitUndefDirectiveTrivia(UndefDirectiveTriviaSyntax node)
        {
        }

        public override void VisitUnsafeStatement(UnsafeStatementSyntax node)
        {
            Visit(node.Block);
        }

        public override void VisitUsingDirective(UsingDirectiveSyntax node)
        {
            Visit(node.Alias);
            Visit(node.Name);
        }

        public override void VisitUsingStatement(UsingStatementSyntax node)
        {
            Visit(node.Declaration);
            Visit(node.Expression);
            Visit(node.Statement);
        }

        public override void VisitVariableDeclaration(VariableDeclarationSyntax node)
        {
            Visit(node.Type);
            VisitSeparatedList(node.Variables);
        }

        public override void VisitVariableDeclarator(VariableDeclaratorSyntax node)
        {
            Visit(node.ArgumentList);
            Visit(node.Initializer);
        }

        public override void VisitWarningDirectiveTrivia(WarningDirectiveTriviaSyntax node)
        {
        }

        public override void VisitWhenClause(WhenClauseSyntax node)
        {
            Visit(node.Condition);
        }

        public override void VisitWhereClause(WhereClauseSyntax node)
        {
            Visit(node.Condition);
        }

        public override void VisitWhileStatement(WhileStatementSyntax node)
        {
            Visit(node.Condition);
            Visit(node.Statement);
        }

        public override void VisitXmlCDataSection(XmlCDataSectionSyntax node)
        {
        }

        public override void VisitXmlComment(XmlCommentSyntax node)
        {
        }

        public override void VisitXmlCrefAttribute(XmlCrefAttributeSyntax node)
        {
            Visit(node.Name);
            Visit(node.Cref);
        }

        public override void VisitXmlElement(XmlElementSyntax node)
        {
            Visit(node.StartTag);
            VisitList(node.Content);
            Visit(node.EndTag);
        }

        public override void VisitXmlElementEndTag(XmlElementEndTagSyntax node)
        {
            Visit(node.Name);
        }

        public override void VisitXmlElementStartTag(XmlElementStartTagSyntax node)
        {
            Visit(node.Name);
            VisitList(node.Attributes);
        }

        public override void VisitXmlEmptyElement(XmlEmptyElementSyntax node)
        {
            Visit(node.Name);
            VisitList(node.Attributes);
        }

        public override void VisitXmlName(XmlNameSyntax node)
        {
            Visit(node.Prefix);
        }

        public override void VisitXmlNameAttribute(XmlNameAttributeSyntax node)
        {
            Visit(node.Name);
            Visit(node.Identifier);
        }

        public override void VisitXmlPrefix(XmlPrefixSyntax node)
        {
        }

        public override void VisitXmlProcessingInstruction(XmlProcessingInstructionSyntax node)
        {
            Visit(node.Name);
        }

        public override void VisitXmlText(XmlTextSyntax node)
        {
        }

        public override void VisitXmlTextAttribute(XmlTextAttributeSyntax node)
        {
            Visit(node.Name);
        }

        public override void VisitYieldStatement(YieldStatementSyntax node)
        {
            Visit(node.Expression);
        }
    }
}